### ISSUE TITLE
enhance wallet connection

### ISSUE THREAD

**Issue by streamerd** [demo-verse/expressions-of-peace#5]
Currently, there are 2 issues around wallet connection.

- When page refreshed, dapp requiring a reconnection
- When first connected, if it was not in Rinkeby network, then requires a page refresh and reconnection to read/write.

Other than that, working fine

**Comment by streamerd** [comment]
following up this one on its branch. 
https://github.com/demo-verse/expressions-editor-react/tree/enhance-wallet-conn

in App.js, [currently added ](https://github.com/demo-verse/expressions-editor-react/commit/281a65bfc3618461335d66d5187097c126ddba91#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67)a network switch (to rinkeby testnet), within the connectHandler function. 

after successfully switching to rinkeby,, when when button to read last expression is clicked, handleRetrieveData function is throwing below error instead reading it from the contract 

(still, only working when page is manually refreshed, could be about provider change/stuck ):

```
Uncaught (in promise) Error: underlying network changed (event="changed", network={"name":"matic","chainId":137,"ensAddress":null}, detectedNetwork={"name":"rinkeby","chainId":4,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (index.ts:261:1)
    at Web3Provider.<anonymous> (base-provider.ts:1178:1)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.ts:1:1)
````

**Comment by streamerd** [comment]
invite @simond110 @thetwosents and inform @KenMan79

**Comment by streamerd** [comment]
fixed with [pull req](https://github.com/demo-verse/expressions-of-peace/pull/6)
